### ISSUE TITLE
Browser detection failures

### ISSUE THREAD

**Issue by JasonBenett** [Ahmdrza/detect-browser#3]
It seems some browser detection currently fail.

For example, the method used to know if the currently browser is Chrome is also verified by Edge. So if you are using Edge, the returned Browser name can be Chrome. The order of the detection steps is important too. If you want, I can make you a pull request to give you my solution to resolve some of the mistakes I found and you can test with your own test cases.

**Comment by Ahmdrza** [comment]
Yeah sure, make a pull request.

**Comment by Ahmdrza** [comment]
I just checked, edge has Edge/17.17134 in its user agent which we can use to detect.
