### ISSUE TITLE
Tagged Version

### ISSUE THREAD

**Issue by ipbc-dev** [Ahmdrza/detect-browser#5]
We're using your code in an Firefox Extension and their guidelines ask to link to specific tagged version of third party libraries, if you could add a tag for the latest version we'd appreciate it very much, thank you.

**Comment by Ahmdrza** [comment]
Hi, I have made tagged version. Thanks.
BTW which extension are you guys developing. I wanna checkout.

**Comment by ipbc-dev** [comment]
Thank you for the quick response. You can find more information about the extension we're developing at https://bittubeapp.com/

**Comment by Ahmdrza** [comment]
Great work. Need some assistance in development, I can offer my services?
