### ISSUE TITLE
Safary

### ISSUE THREAD

**Issue by gribchic** [Ahmdrza/detect-browser#6]
`if (/constructor/i.test(window.HTMLElement) || (function (p) {
		return p.toString() === '[object SafariRemoteNotification]';
	})(!window['safari'])) {
		return 'Safari';
	}`

the code `!window['safari']` will always return true or false, so the code  `p.toString()` will always return 'true' or 'false', so the code `p.toString() === '[object SafariRemoteNotification]'` will always return false.

Am I right?

**Comment by Ahmdrza** [comment]
No. Please test on safari console. You will get proper outputs there.
